

- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest 
    update_cache: yes 
    force_apt_get: yes

- name: Install required system packages
  apt: 
    name: "{{ item }}"
    state: latest 
    update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: docker-ce 
    state: latest

- name: update apt cache
  become: true
  become_method: sudo 
  apt:
    update_cache: yes

# sudo groupadd docker
- name: Create "docker" group
  group:
    name: "{{ docker_group }}"
    state: present

# sudo usermod -aG docker root
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "{{ remote_user }}"
    group: "{{ docker_group }}"
    append: yes


- name: Pull default Docker image
  become: yes
  become_user: "{{ remote_user }}"
  docker_image:
    name: "{{ default_container_image }}"
    source: pull

    # Creates the number of containers defined by the variable create_containers, using values from vars file
#- name: Create default containers
#  become: yes
#  become_user: ubuntu
#  docker_container:
#    name: "{{ default_container_name }}{{ item }}"
#    image: "{{ default_container_image }}"
#    command: "{{ default_container_command }}"
#    state: present
#  with_sequence: count={{ create_containers }}