- name: install system packages
  become: true
  become_method: sudo 
  apt:
    name: "{{ item }}"
    state: latest
  when:
    - ansible_facts['distribution'] =="Ubuntu"
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - python3-setuptools
  
    